.TAOS-CI/.gbs.conf, src/libsensor/edge_sensor.c
- Add gbs conf file
Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>
=> [CI] Add gbs conf file and fix indent

debian/control
Add missing package for debian build.
- Remove glib package later.
=> [Debian] Add missing package

.ahub/tcchecker-tca/config.yaml
Change tcc name to nnstreamer-edge.
=> [Test] update tcm config

packaging/nnstreamer-edge.spec
Fix build error, temporal block the unittest.
=> [Build] fix build error on tizen

CMakeLists.txt, debian/changelog, debian/rules, packaging/nnstreamer-edge.spec
Update version to 0.1.0 and add note about version information.
=> [Edge] version info

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Set arg - base type of edge-data handle.
=> [Edge] size of data handle

.clang-format
Add clang format file
- Copied from nnstreamer repo
=> [Style] Add clang format file

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Prevent receive failure, update source to validate edge command.
=> [Edge] validate command

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Fix svace issue, add unlock before return.
=> [Svace] fix svace issue

README.md
- Add nnstreamer-edge coverage badge.
=> [README] Add coverage badge.

.github/workflows/ubuntu_clean_cmake_build.yml
Add the most simple github-action build test script
=> [github-action] add ubuntu cmake clean build

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Check return value of the socke lib function.
=> [Coverity] Check return value

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/unittest_nnstreamer-edge.cc
Remove unnecessary param in edge APIs and fix error case.
=> [Edge] unnecessary param and error case

tests/unittest_nnstreamer-edge.cc
Add basic testcases about edge event functions.
=> [Test] unittest about edge event

.github/workflows/ubuntu_clean_cmake_build.yml
Add apt-get install for dependencies.
Tested: https://github.com/myungjoo/nnstreamer-edge/actions/runs/2621118870
=> [github-action] add depedencies for ubuntu/cmake.

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c
Add macro to check valid string.
=> [Util] macro to check string

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Check socket state before sending/receiving the edge command.
=> [Socket] condition to check socket

src/libnnstreamer-edge/nnstreamer-edge-internal.c
pthread_join can wait joinable thread.
So, change thread attribute.
=> [Edge] Change thread attribute

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Set flag to send/receive command and capability between server and client.
=> [Connection] cmd between server and client

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h
Add util function to get available port.
TODO: update testcase (data transfer with fixed port) later.
=> [Util] function to get port number

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Update src to close socket and release msg thread.
GSocket will close socket automatically if its ref count is 0.
=> [Socket] condition to release thread

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c
Remove glib, check mem ptr to release allocated memory.
=> [Util] macro safe-free

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c
Replace caps info instead of appedning the string.
=> [Edge] Replace caps info

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h, tests/unittest_nnstreamer-edge.cc
Code clean, fix indent and update description / log message.
=> [CodeClean] update indent and description

tests/unittest_nnstreamer-edge.cc
Add testcase for edge connection and data transfer between local server and client.
=> [Test] connect to local @open sesame 07/20 14:28

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt.c
Update source to remove dependency to glib.
=> [CodeClean] remove glib function

src/libnnstreamer-edge/nnstreamer-edge-internal.c
In message thread, remove connection data when received error from client.
Internally error command means closing socket.
=> [Edge] remove client when received error

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Handle connection closed case, connection info in hashtable is null.
=> [Edge] handle connection failure case

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-common.h
Remove glib, add internal log function.
=> [Log] internal log function

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h, src/libnnstreamer-edge/nnstreamer-edge-mqtt.c, tests/unittest_nnstreamer-edge.cc
Add error case if given port number is invalid.
=> [Edge] handle invalid port number

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h, tests/unittest_nnstreamer-edge.cc
Replace hashtable (glib) to list, setting/getting metadata of edge handle.
=> [Meta] list for metadata

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h
Add mutex lock in data handle and update function description.
=> [Data] lock in data handle

src/libnnstreamer-edge/nnstreamer-edge-common.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h, src/libnnstreamer-edge/nnstreamer-edge-mqtt.c
- Implement query mqtt hybrid feature.
=> [MQTT] Implement query mqtt hybrid feature

src/libnnstreamer-edge/nnstreamer-edge-internal.c
- Initialize the command info.
=> [Coverity] Initialize the command

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt.c
Fix svace issue, handle error case if memory allocation is failed.
=> [CodeClean] handle allocation failure case

tests/unittest_nnstreamer-edge.cc
Add testcases to set/get the info from edge handle.
=> [Test] info from edge handle

src/libnnstreamer-edge/nnstreamer-edge-mqtt.c, tests/unittest_nnstreamer-edge.cc
Remove callbacks for connection, waiting for connection or disconnection state.
=> [MQTT] remove connection cb

tests/unittest_nnstreamer-edge.cc
Add testcases to handle error case of serialization in edge-data.
=> [Test] testcase for serialization of edge-data

CMakeLists.txt, packaging/nnstreamer-edge.spec
Add features for tizen build - mqtt and dlog.
=> [Spec] features for tizen release

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-internal.c
Code clean, prepare socket impl without glib.
=> [CodeClean] param to send/recv data

CMakeLists.txt, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h
Update code - socket connection, remove gio library.
=> [Socket] remove gio lib

src/libnnstreamer-edge/nnstreamer-edge-internal.c
- Set listerner host address given from user.
- Set thread running flag before close the connection.
* Tested with nnstreamer repo.
=> [Listener] Set listerner host address

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Temporarily disable unimportant messages.
TODO: Set log level.
=> [Log] Temporarily disable unimportant messages

.github/workflows/tizen.gbs.conf, .github/workflows/tizen_integration_test.yml
Build & run test cases of nnstreamer to test
the integrity between nnstreamer-edge and nnstreamer.
@gichan-jang : this is the test case I've mentioned.
=> github-action: integration test w/ nnstreamer

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Code clean, change var type (bool) and define internal function to fill socket address struct.
=> [CodeClean] function to fill socket addr struct

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Change data type to print client ID.
=> Format to print client ID

src/libnnstreamer-edge/nnstreamer-edge-mqtt.c
Replace g-async-queue to internal queue in MQTT functions.
=> [MQTT] replace glib queue

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-util.c, src/libnnstreamer-edge/nnstreamer-edge-util.h
Remove glib, add util function to generate client ID.
=> [Util] generate client ID

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h
Add new thread to send data asynchronously.
=> [Transfer] thread to send data

tests/unittest_nnstreamer-edge.cc
Remove glib main-loop and unnecessary thread in testcases.
=> [Test] remove main loop

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h
Add list of connection data and remove glib table.
=> [Connection] list of connections

include/nnstreamer-edge.h
- Add elaborate edge API description.
- Add example code.
=> [Edge] Elaborate edge API description.

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h, tests/unittest_nnstreamer-edge.cc
- Adding serialize and deserialize the edge data.
- Add unittest for serialize the data.
=> [Common] Adding serialize/deserialze the edge data.

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h
Update doc, typo and remove todo items those are already implemented.
=> [Doc] fix typo and remove todo item

.github/workflows/tizen.gbs.conf
The build infra has updated and its binary repository URL
has been updated.
=> github-action/gbs: Tizen build infra update

src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/unittest_nnstreamer-edge-aitt.cc
Serialize the edga data before send using AITT.
=> [AITT] Serialize the data before send

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h, tests/unittest_nnstreamer-edge-aitt.cc, tests/unittest_nnstreamer-edge.cc
- If no client_id is found in the data, publish it to all connected clients.
- Add NNS_EDGE_FLAG_PUBSUB.
Signed-off-by: Yechan Choi <yechan9.choi@samsung.com>
=> [Edge] support edge

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Fix invalid param, data handle ptr.
=> [Bug] invalid data ptr

.TAOS-CI/.gbs.conf, packaging/nnstreamer-edge.spec
Code clean, add definition - features for TV release.
=> [Spec] features for TV release

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Code clean, fix coverity issue and prevent error case.
=> [CodeClean] prevent error case

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Fix build-test error on TizenRT, header and undefined symbol.
=> [Build] error on TizenRT @open sesame 09/29 16:56

tools/build_TizenRT/Kconfig, tools/build_TizenRT/Make.defs, tools/build_TizenRT/Makefile, tools/build_TizenRT/README.md
Add make file and document to run build-test on TizenRT.
=> [Doc] build-test on TizenRT

CMakeLists.txt, debian/changelog, packaging/nnstreamer-edge.spec
Release 0.1.0 for Tizen 7.0 M2. Start impl for next release (0.2.1).
=> [Version] update version to 0.2.1 @open sesame 9/30 12:40

src/libnnstreamer-edge/nnstreamer-edge-aitt.c
Code clean, report error when building aitt impl without feature definition.
=> [Aitt] check feature definition

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-util.c, src/libnnstreamer-edge/nnstreamer-edge-util.h
Add macro to check port number.
=> [Util] macro to check port number

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Update code to handle sock event in recv thread.
=> [Sock] event in recv thread

src/libnnstreamer-edge/nnstreamer-edge-queue.h
- Add missing doxygen bug tag.
=> [Doxygen] Add missing tag

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-queue.c, src/libnnstreamer-edge/nnstreamer-edge-queue.h, tests/unittest_nnstreamer-edge.cc
Set max number in queue when sending data to other node.
=> [Queue] limit in data queue

include/nnstreamer-edge.h, src/CMakeLists.txt, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-log.c, src/libnnstreamer-edge/nnstreamer-edge-log.h, src/libnnstreamer-edge/nnstreamer-edge-util.c, tools/build_TizenRT/Makefile
Add new function to set log level.
=> [Log] set log level

src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, tests/unittest_nnstreamer-edge.cc
Implement mqtt using moosquitto lib.
=> [MQTT] Implement mqtt using mosquitto lib

jni/nnstreamer-edge.mk
- Add `android.mk` file for NNStreamer Android build
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>
=> [build] Add android.mk file for Android build

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-queue.c, src/libnnstreamer-edge/nnstreamer-edge-queue.h, tests/unittest_nnstreamer-edge.cc
Add leaky option in nns-edge queue.
=> [Queue] leaky option

tools/build_TizenRT/Kconfig, tools/build_TizenRT/Makefile, tools/build_TizenRT/README.md
- Build mqtt-hybrid on TizenRT.
=> [TizenRT] Build mqtt-hybrid

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-metadata.c
Code clean, remove unnecessary condition and fix var type.
=> [CodeClean] unnecessary cond

tests/unittest_nnstreamer-edge-aitt.cc
Fix invalid function in aitt testcase.
=> [Test] invalid function in aitt test

README.md
Add dailt build badge
- target: tizen, tizenRT, ubuntu
=> [README] Add daily build badge @open sesame 11/02 16:20

src/libnnstreamer-edge/nnstreamer-edge-aitt.c
Fix build error, AITT updated param type in subsribe callback.
=> [AITT] fix param type

src/libnnstreamer-edge/nnstreamer-edge-data.c, src/libnnstreamer-edge/nnstreamer-edge-data.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c
Code clean, add wrapper function to release edge-data handle.
=> [Data] wrapper function to release data handle

src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c
Code clean, handle error case if failed to create mosquitto handle.
=> [CodeClean] error case in mosquitto impl

src/libnnstreamer-edge/nnstreamer-edge-aitt.c
Code clean,
1. change aitt-handle (handle in aitt header)
2. update log message
=> [CodeClean/AITT] unnecessary aitt handle type

src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-event.c, src/libnnstreamer-edge/nnstreamer-edge-event.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c
Add util function to invoke edge-event callback.
=> [CodeClean/Event] util to invoke event

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt.h, tests/unittest_nnstreamer-edge.cc
Code clean, add broker handle and revise MQTT functions. This will remove dependency to edge-handle in MQTT impl.
=> [CodeClean/MQTT] broker handle

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt.h, src/libnnstreamer-edge/nnstreamer-edge-queue.c, src/libnnstreamer-edge/nnstreamer-edge-queue.h, tests/unittest_nnstreamer-edge.cc
Code clean, prepare next PR. Handle data size of queue.
=> [CodeClean/Queue] handle data size

src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-aitt.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/unittest_nnstreamer-edge-aitt.cc
Separate AITT handle and update related code, to remove dependency to nns-edge handle.
=> [AITT] separate handle

tests/unittest_nnstreamer-edge.cc
Code clean, remove unnecessary host info to run mqtt connection.
=> [Test] remove unnecessary info

src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c, src/libnnstreamer-edge/nnstreamer-edge-util.c
Change log level fron info to debug.
=> [MQTT/temporal] Change log level 

src/libnnstreamer-edge/nnstreamer-edge-data.c, src/libnnstreamer-edge/nnstreamer-edge-data.h, tests/unittest_nnstreamer-edge.cc
Add util function to check serialized data ptr.
=> [Data] util to check serialized data

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-queue.c
1. Add flag to check sending thread.
2. Init data ptr and size in the queue.
=> [Connect] flag to check sending thread

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Fix returned code after creating a thread.
=> [Common] fix ret code after creating a thread

src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-data.c, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-metadata.c, src/libnnstreamer-edge/nnstreamer-edge-queue.c, tests/unittest_nnstreamer-edge-aitt.cc, tests/unittest_nnstreamer-edge.cc
Set NULL after release the memory.
=> Safe momory free

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-queue.c, src/libnnstreamer-edge/nnstreamer-edge-queue.h
- Release send queue after the send thread is finished.
- Set timeout for send queue to terminate the send thread.
=> Change queue of the sending thread

src/libnnstreamer-edge/nnstreamer-edge-queue.c
Code clean, remove duplicated code to clear data.
=> [Queue] clear data when releasing the queue

src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c
Change queue name from server_list to message_queue to handle not only server information but also the raw data later.
=> [MQTT] Change queue name

src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/unittest_nnstreamer-edge.cc
Add internal flag to check edge-handle is started.
=> [Api] flag to check state - started

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c
Handle error case, add line comment and fix build error.
=> [CodeClean] handle error case

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c
Fix svace issues, handle res leak.
=> [CodeClean] fix res leak case

README.md
Add quick start guide
- install nnstreamer-edge via ppa
- build and run unit tests
=> [README] Add quick start guide

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt.h, tests/unittest_nnstreamer-edge-mqtt.cc
Change timeout for getting message from mqtt broker.
default timeout: 0 (infinite timeout)
=> [MQTT] Change timeout for getting message from mqtt broker

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Fix svace issue. The function gethostbyname is unsafe function, use getaddrinfo instead.
=> [Socket] use getaddrinfo to fill socketaddr

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt.h, tests/unittest_nnstreamer-edge.cc
Code clean, fix indent and remove unnecessary lines.
=> [CodeClean] remove unnecessary code

CMakeLists.txt, debian/changelog, packaging/nnstreamer-edge.spec
This is new LTS release for TizenRT.
=> Release of 0.2.2, LTS for TizenRT

CMakeLists.txt, debian/changelog, packaging/nnstreamer-edge.spec
Update version, devel v2.3.0 for Tizen 8.0.
=> [Build] start devel of 0.2.3

tests/unittest_nnstreamer-edge-mqtt.cc
Add negative test of set-event in mqtt impl.
=> [Test] negative case to set mqtt event

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c
Adds API that checks the connection of given edge handle.
=> Add connection check API

include/nnstreamer-edge.h
Code clean, fix typo in edge header.
=> [CodeClean] fix typo

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-data.c, tests/unittest_nnstreamer-edge.cc
Add function to clear raw data in edge data.
This does not release the edge data handle.
=> [Data] Add data clear function

src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt.h, tests/unittest_nnstreamer-edge-mqtt.cc, tests/unittest_nnstreamer-edge.cc
Code clean, update param name - broker handle.
=> [MQTT] update handle name

src/libnnstreamer-edge/nnstreamer-edge-queue.c, src/libnnstreamer-edge/nnstreamer-edge-queue.h, src/libnnstreamer-edge/nnstreamer-edge-util.h
Update macro to wait timed-out condition.
=> [Util] macro to wait condition

src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c
Change to wait until removing the retained message.
=> [MQTT] Wait until removing the retained message. @open sesame 08/23 13:10

src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c
Add function to clear retained message, and set wait-time interval.
=> [MQTT] function to clear retained msg

CMakeLists.txt, debian/changelog, packaging/nnstreamer-edge.spec
Update version to 0.2.4, Tizen M2 release.
=> [Release] update version

src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-aitt.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/unittest_nnstreamer-edge-aitt.cc
- Add set/get option of AITT.
- Add releated unittests.
*Waiting for AITT tizen release.
=> [AITT] set/get option for AITT @open sesame 09/14 10:43

src/libnnstreamer-edge/nnstreamer-edge-aitt.c
Code clean, macro to check input param.
=> [CodeClean] validate str param

CMakeLists.txt, debian/changelog, packaging/nnstreamer-edge.spec
Update version, start implementation for next release.
=> [Release] start impl for next release

src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-aitt.h
- Add publish_full
- Set default protocol as AITT_TCP
=> [AITT] Add publish_full

src/libnnstreamer-edge/nnstreamer-edge-internal.c
It is necessary to consider the case of failing to generate Metadata
when creating the Edge handle. It is not good to deliver Edge handles
that have not been created normally to the user.
=> [Edge] Add metadata creation exception handling

tests/unittest_nnstreamer-edge.cc
nns_edge_queue_h handle is always used tests related queue.
Using the fixture provided by gtest, the redundant code is
eliminated by separating repetitive tasks of allocating and
releasing queue handles.
=> [Test] Add queue fixture class

src/libnnstreamer-edge/nnstreamer-edge-internal.c
- Add a pthread_cond for nns_edge_handle. And let the start method wait for the cond to be signaled by send_thread.
- This prevents some race conditions when APIs are used while send_thread is not yet started.
=> [Edge] Add cond for nns_edge_handle

src/libnnstreamer-edge/nnstreamer-edge-internal.c
If current connection is lost, find available node and reconnect. 
Previously, This recovery work is done by user application. 
Let's make the users don't care about this work when using MQTT-HYBRID.
*edgesrc and tensor_query_* should be updated after this change.
=> [Hybrid] Reconnect to available node

src/libnnstreamer-edge/nnstreamer-edge-aitt.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c, src/libnnstreamer-edge/nnstreamer-edge-queue.c
Add lock to wait for creating new thread for data transfer.
=> [Common] wait for thread with lock

packaging/nnstreamer-edge.spec
This patch disables the mqtt option in the case of DA products.
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped
=> [Spec] Disable mqtt option for DA products

.github/workflows/_typos.toml, .github/workflows/spell-checker.yml, packaging/nnstreamer-edge.spec, src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-data.c, src/libnnstreamer-edge/nnstreamer-edge-data.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt.h, tests/unittest_nnstreamer-edge.cc
Add spell checker github action.
1. Build test: [ *]Passed [ ]Failed [ ]Skipped
2. Run test: [ *]Passed [ ]Failed [ ]Skipped
=> [Actions] Add spell checker

include/nnstreamer-edge.h
Update header file - fix param and return code.
=> [Doc] update description

include/nnstreamer-edge-data.h, include/nnstreamer-edge-event.h, include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-queue.h
Code clean, update tags and API description.
=> [Doc] update API description

include/nnstreamer-edge-event.h, src/libnnstreamer-edge/nnstreamer-edge-event.c, tests/unittest_nnstreamer-edge.cc
Add util function to get the edge event data, and remove unnecessary return code.
=>  [Event] util to get data

tests/unittest_nnstreamer-edge.cc
Fix build warning, remove unnecessary local variable.
=> [CodeClean/Test] unnecessary local variable

src/libnnstreamer-edge/nnstreamer-edge-custom-impl.c
Code clean, check invalid param case in custom connection.
=> [CodeClean] check invalid param

tests/unittest_nnstreamer-edge-custom.cc
Code clean, fix mem leak case in custom connection test.
=> [Test] fix mem leak

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Fix segfault case,
1. stop sending thread before closing connection handle.
2. handle error case while pushing edge data into sending queue.
=> [CodeClean] fix segfault case

CMakeLists.txt, jni/nnstreamer-edge.mk, packaging/nnstreamer-edge.spec, src/CMakeLists.txt, src/libnnstreamer-edge/nnstreamer-edge-custom-impl.h, tests/CMakeLists.txt
Add new definition to support custom connection (default on).
=> [Custom] feature for custom connection

.github/workflows/daily-build-gbs.yml
To incerease test coverage of mqtt, let's install mosquitto broker.
1. Build test: [*]Passed [ ]Failed [*]Skipped
2. Run test: [*]Passed [ ]Failed [*]Skipped
=> [Action] Run mosquitto broker

include/nnstreamer-edge-custom.h, include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-custom-impl.c, src/libnnstreamer-edge/nnstreamer-edge-custom-impl.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/nnstreamer-edge-custom-test.c, tests/unittest_nnstreamer-edge-custom.cc
- Add stop discovery function
- Rename discover to start_discovery
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped
=> Add stop discovery function

include/nnstreamer-edge-custom.h, src/libnnstreamer-edge/nnstreamer-edge-custom-impl.c, src/libnnstreamer-edge/nnstreamer-edge-custom-impl.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/nnstreamer-edge-custom-test.c, tests/unittest_nnstreamer-edge-custom.cc
- Add disconnection function for custom connection
- Add unit test
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped
=> [Custom] Add disconnect function for custom connection
