.github/CODEOWNERS
Add code owners for the edge repo. Define specified owner later.
=> [github] Add CODEOWNER file

LICENSE, packaging/nnstreamer-edge.spec
This patch adds the omitted LICENSE to the rpm package. This file is
mandatory for Tizen.org.
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>
```bash
$ rpm -qlp nnstreamer-edge-0.0.1-1.armv7l.rpm
/usr/lib/libnnstreamer-edge.so
/usr/lib/libnnstreamer-edge.so.0.0.1
/usr/share/licenses/nnstreamer-edge
/usr/share/licenses/nnstreamer-edge/LICENSE
```
=> [Pkg] Add LICENSE file to rpm package

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h
1. When releasing handle, close socket listener.
2. Remove cancelable, we do not use it.
=> [Edge] close listener in handle

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Prevent error case, handle memory limit when receiving data from socket.
=> [Svace] prevent warning

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h, tests/unittest_nnstreamer-edge.cc
Update edge interfaces.
- request/respond functions are unnecessary as it can send a data by using publish.
- subscribe does not require data handle.
- define connect-type and flags for future work.
=> [Interface] update edge interface

src/libnnstreamer-edge/nnstreamer-edge-common.c, src/libnnstreamer-edge/nnstreamer-edge-common.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h, src/libnnstreamer-edge/nnstreamer-edge-mqtt.c
1. Do not replace topic string in edge handle (set topic in mqtt-handle).
2. Use util function to get/parse host string.
3. Fix res leak case when mqtt connection is failed.
4. Code clean, remove unnecessary conversion after allocating new memory for mqtt-handle.
=> [MQTT] topic in broker handle

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/unittest_nnstreamer-edge.cc
Prepare interface udpate,
- rename publish() to send()
- remove testcase - no client ID in data (If data handle does not have client ID, it will send data to all connected nodes.)
=> [Interface] rename (publish to send)

tests/unittest_nnstreamer-edge.cc
1. Add assertion when allocating memory for test-data is failed.
2. Replace g_free.
=> [Test] alloc failure case

packaging/nnstreamer-edge.spec
Clearly define build-require to mosquitto, to run unittest using mqtt broker.
=> [Build/Test] add mosquitto to run test

packaging/nnstreamer-edge.spec, tests/unittest_nnstreamer-edge-aitt.cc, tests/unittest_nnstreamer-edge.cc
- Exclude Aitt related files when aitt_support is not set.
- Remove unused variable and change test name.
=> [packaging] Exclude Aitt related files when aitt_support is not set.

include/nnstreamer-edge.h
Remove macro - publish(), use send() instead.
=> [API] remove deprecated func

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Since the timeout of the poll is set to 0, let's not check the return value of 0.
=> [Edge] Fix checking return value of the poll().

src/libnnstreamer-edge/nnstreamer-edge-internal.c
- Remove `pthread_cancel`, cause msg and listener thread do not handle thread cancellation.
- By the way, Android NDK does not support `pthread_cancel`.
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>
=> [edge] Remove unnecessary pthread call

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-data.c, src/libnnstreamer-edge/nnstreamer-edge-data.h, src/libnnstreamer-edge/nnstreamer-edge-event.c, src/libnnstreamer-edge/nnstreamer-edge-event.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-internal.h, src/libnnstreamer-edge/nnstreamer-edge-metadata.c, src/libnnstreamer-edge/nnstreamer-edge-metadata.h, src/libnnstreamer-edge/nnstreamer-edge-util.c, src/libnnstreamer-edge/nnstreamer-edge-util.h, tests/unittest_nnstreamer-edge-aitt.cc, tests/unittest_nnstreamer-edge.cc
An error occurs in the communication because of different data sizes in the 32-bit and the 64-bit systems. Fixate the data size.
Tested using 32bit Tizen TV and 64bit Ubuntu.
=> Fixate the data size @open sesame 10/14 10:07

src/libnnstreamer-edge/nnstreamer-edge-queue.c, src/libnnstreamer-edge/nnstreamer-edge-queue.h
Code clean,
1. fix mem leak case - max buffer in queue.
2. use common destroy callback.
=> [Queue] fix mem leak case

CMakeLists.txt
It should be given as the optional mode argument.
Refer to https://cmake.org/cmake/help/v3.0/command/message.html
=> CMake: FATAL_ERROR should not be in message string. @open sesame 11/03 10:43

jni/nnstreamer-edge.mk, src/libnnstreamer-edge/nnstreamer-edge-log.c
- Add DEBUG macro value as 0 if it is not defined before
- Add the source file to the source list in Android.mk
=> [build] Add nnstreamer-edge-log.c to android build 

src/libnnstreamer-edge/nnstreamer-edge-util.c
Fix svace issue, size_t in nns-edge was changed to unsigned int 64. Fix invalid arg type to print log.
=> [CodeClean] invalid arg type

src/libnnstreamer-edge/nnstreamer-edge-data.c, src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-metadata.c, src/libnnstreamer-edge/nnstreamer-edge-util.c, src/libnnstreamer-edge/nnstreamer-edge-util.h
Fix svace issue - size limit to allocate memory.
Add util function for mem allocation, checking max size before calling malloc.
=> [Util] util function to allocate memory

src/libnnstreamer-edge/nnstreamer-edge-aitt.c, src/libnnstreamer-edge/nnstreamer-edge-data.c, src/libnnstreamer-edge/nnstreamer-edge-data.h, src/libnnstreamer-edge/nnstreamer-edge-metadata.c, src/libnnstreamer-edge/nnstreamer-edge-metadata.h, tests/unittest_nnstreamer-edge.cc
Code clean,
1. handle data size to deserailze edge data.
2. Fix typo and revise testcases.
=> [CodeClean/Data] param to deserialize edge-data

tools/build_TizenRT/Makefile
Remove object files that are the result of TizenRT build when cleaning.
=> [TizenRT] Remove object file when cleaning

tests/unittest_nnstreamer-edge.cc
When running the test, the memory is not released,
fx the memory-leak by releasing the memory before the end of the test.
=> [Test] fix memory leak

.gitignore
This patch is to ignore cmake related files generated after the build.
=> [Git] Add ignore list related with CMake

src/libnnstreamer-edge/nnstreamer-edge-internal.c
'JOINABLE' is the default atribute of the pthread, so remove the attribute.
*note: Some TizenRT board don't support this option.
=> [Edge] Remove unnecessary pthread attribute.

CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
Move the NNS_EDGE_LIB_NAME variable from the src/CMakeLists.txt to
CMakeLists.txt in the root directory.
Since the nnstreamer-edge value is also referenced in the
tests/CMakeLists.txt file, change the variable to use in common to
minimize human errors.
=> [Build] Move NNS_EDGE_LIB_NAME variable to root CMakeLists.txt

README.md
pkgconfig was being installed on the wrong path.
now, pkgconfig path is CMKAE_INSTALL_PREFIX/lib/pkgconfig
=> [CMAKE] Modify guidelines for Build and Run test @open sesame 07/12 16:43

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Internal fix to set fixed size of edge-cmd struct.
=> [Cmd] use fixed size in cmd struct

src/libnnstreamer-edge/nnstreamer-edge-data.c, src/libnnstreamer-edge/nnstreamer-edge-internal.c
Add version info while sending and receiving buffer between edge connection.
TODO:
Now max memories in edge-data is 16. Check the limit when updating this definition.
=> [Cmd] version info in buffer

src/libnnstreamer-edge/nnstreamer-edge-internal.c
[DEBUG] string is unnecessary, nns_edge_logd() function
display DEBUG log level with log.
=> [Edge] Remove '[DEBUG]' log format string

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c, src/libnnstreamer-edge/nnstreamer-edge-queue.c, src/libnnstreamer-edge/nnstreamer-edge-queue.h, tests/unittest_nnstreamer-edge.cc
The return type is changed from boolean to nns_edge_error_e type
in the same way as other modules. These changes provide uniformity
when using APIs, reducing confusion for developers.
=> [Queue] Unify return format to nns_edge_error_e

include/nnstreamer-edge.h, src/libnnstreamer-edge/nnstreamer-edge-util.c, tests/unittest_nnstreamer-edge-aitt.cc, tests/unittest_nnstreamer-edge.cc
- set available port when user set port to '0'
- ml service api set '0' as the default port if the port isn't set
but '0' is an invalid port
=> [bugfix] Change the range of valid port

include/nnstreamer-edge.h
nnstreamer now supports max 256 tensors in the buffer.
Increase max memories in nnstreamer-edge handle.
TODO:
We will fix the util functions in edge elements of nnstreamer, to handle memories in gst-buffer.
=> [Common] max memories in nns-edge

include/nnstreamer-edge.h, jni/nnstreamer-edge.mk, src/CMakeLists.txt, src/libnnstreamer-edge/nnstreamer-edge-log.c, src/libnnstreamer-edge/nnstreamer-edge-log.h, src/libnnstreamer-edge/nnstreamer-edge-util.c
When outputting dlog using dlogutil in Tizen, garbage values are output in the format starting with %
=> [bugfix] Modify dlog output code

src/libnnstreamer-edge/nnstreamer-edge-mqtt-mosquitto.c, src/libnnstreamer-edge/nnstreamer-edge-mqtt-paho.c
Clearly set connection state and handle when closing MQTT connection.
=> [MQTT] clearly set null when closing connection

.github/workflows/tizen_integration_test.yml
Current, gbs build system build nnstreamer-edge only in x86-64 architecture. 
This patch is to support to build x86_64, i586, armv7l aarch64 architecture
=> github-action/gbs: Build nnstreamer-edge based all architecture

packaging/nnstreamer-edge.spec
Remove AITT connection from nnstreamer-edge because AITT is removed from Tizen platform.
* Remove nnstreamer-edge-aitt.c later.
* 
Signed-off-by: gichan2-jang <gichan2.jang@samsung.com>
=> [AITT] Remove AITT

packaging/nnstreamer-edge.spec
Due to the lcov 2.0 upgrade, the warning is changed to error so the gcov build fails. Ignore this case. (Tizen PM guide)
=> [Tizen] Fix gcov build error

src/libnnstreamer-edge/nnstreamer-edge-internal.c
In _nns_edge_transfer_data(), there is no checking return value.
It is difficult to check when a problem occurs during the data transmission process,
so check return values and add logs when problems occur.
=> [Edge] Add checking return value

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/ISSUE_TEMPLATE/Support_request.md, .github/PULL_REQUEST_TEMPLATE.md
This PR is to create a templates to autemate issue and PR process.
Issue and PR templates still use the format of the parent project, nnstreamer, for uniformity.
(https://github.com/nnstreamer/nnstreamer/tree/main/.github)
=> [Github] Add issue and pull request templates

src/libnnstreamer-edge/nnstreamer-edge-internal.c
- Let the edge wait listener_thread to be properly started.
- This fix occasional hangs when nns_edge_release_handle called.
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped
=> [common] Let edge wait listener thread to be started.

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Code clean,
- fix indent and mem leak case.
- check invalid custom handle case.
=> [Custom] fix leak case

include/nnstreamer-edge-custom.h, jni/nnstreamer-edge.mk, src/CMakeLists.txt, src/libnnstreamer-edge/nnstreamer-edge-custom-impl.c, src/libnnstreamer-edge/nnstreamer-edge-custom-impl.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/nnstreamer-edge-custom-test.c
Separate custom connection implementation and update callbacks.
=> [Custom] separate custom impl

src/libnnstreamer-edge/nnstreamer-edge-internal.c, src/libnnstreamer-edge/nnstreamer-edge-queue.c, src/libnnstreamer-edge/nnstreamer-edge-queue.h, tests/unittest_nnstreamer-edge.cc
Change function param, return error code when getting queue len.
=> [Queue] change param

src/libnnstreamer-edge/nnstreamer-edge-queue.c, tests/unittest_nnstreamer-edge.cc
Set magic when creating/destroying the queue handle.
=> [Queue] set magic in handle

CMakeLists.txt, debian/changelog, packaging/nnstreamer-edge.spec, tools/build_TizenRT/Makefile
Prepare Tizen 9.0 M2 release, update version.
=> [Release] update version

src/libnnstreamer-edge/nnstreamer-edge-internal.c
Code clean, remove unnecessary header and print log for custom connection.
=> [CodeClean] unnecessary header

.github/workflows/gen_coverage_badge.py
This patch adds missing python script gen_coverage_badge.py
This fixes failed https://github.com/nnstreamer/nnstreamer-edge/actions/workflows/daily-build-gbs.yml
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [*]Skipped
=> [action] add missing python script

src/libnnstreamer-edge/nnstreamer-edge-custom-impl.c, src/libnnstreamer-edge/nnstreamer-edge-custom-impl.h, src/libnnstreamer-edge/nnstreamer-edge-internal.c, tests/unittest_nnstreamer-edge-custom.cc
Define handle for custom connection to hide internal structure.
=> [Custom] handle for custom connection

packaging/nnstreamer-edge.spec
Test coverage resultes are not printed.
Current: https://nnstreamer.github.io/testresult/nnstreamer-edge/
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped
=> [Test] Fix test coverage generation failure

README.md
Change code coverage result repo from TAOS-CI to github.io
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [*]Skipped
=> [README] Change code coverage result repo

src/libnnstreamer-edge/nnstreamer-edge-internal.c
For TCP or MQTT, let pub node skip the connection request.
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped
=> Skip connection request
